In [ ]:
%config IPCompleter.greedy=True

# Jovani's Analysis

> In which cities can millenials have their avocado toast AND buy a home?

My Plan ...

I would first like to do a couple of things:

- [ ] Checkout the data
- [ ] Fix the data types of any of the columns
- [ ] Create a new pickle file with the data I find important
- [ ] ...

In [47]:
# import all the Python libraries that I would relying for...
import numpy as np
import pandas as pd
import os

# File to Load (Remember to change the path if needed.)
avocado_data_to_load = os.path.join("./data/raw", "avocado.csv")

In [48]:
# Data Frame Creation
# Knowing that the data is tabluar and is coming in a CSV file
# I will automatically go into using a dataframe for EDA but first Cleaning.
king_guacate_df = pd.read_csv(avocado_data_to_load)
king_guacate_df

Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

I want to get a feel for the columns and data values that would pertain to the question we are trying to answer:

In which cities (location) can millenials (demographics) have their avocado (product) toast AND buy a home (product)?

So the union of:

- Location having the
    - Demogrpahics purchasing
        - avocados
        - homes

Currently this datasets has Total Volume of avocados sold by date and location, by type, and at the average price.

In [49]:
# Viewing the Data
# I want to inspect the columns and general type information of the DF
print(king_guacate_df.info)
print(king_guacate_df.columns)
print(king_guacate_df.index)

<bound method DataFrame.info of        Unnamed: 0        Date  AveragePrice  Total Volume     4046       4225  \
0               0  2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1  2015-12-20          1.35      54876.98   674.28   44638.81   
2               2  2015-12-13          0.93     118220.22   794.70  109149.67   
3               3  2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4  2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...         ...           ...           ...      ...        ...   
18244           7  2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8  2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9  2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10  2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11  2018-01-07          1.62      17489.58  2894.77    2356.13

Steps to cleaning the data:

 - In a tabular data format (CSV, Excel, etc) - no blank columns, no blank rows, no merged cells (Excel), and the column data needs to be normalized (same data and correct data type).
 - Tabular data issues and data quality: noise, outliners, and duplicate data.
 - Get a sense of the distributions in the data - What is the distribution of "'AveragePrice', 'Total Volume', '4046', '4225', '4770', 'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags'"
    - BUT would we want to go through all that work or make assumptions up front cut out some of the columns and strictly focus on a select few.

In [50]:
# Let us start changing the data types of the columns
# We want to make a couple of data type changes to the columns
# Date to date
# type, year, region to categories
# AveragePrice, Total Volume, 4046, 4225, 4770, Total Bags, Sm, l, xl Bags keep to float64
king_guacate_df["Date"] = pd.to_datetime(king_guacate_df["Date"])
king_guacate_df["type"] = king_guacate_df["type"].astype("category")
king_guacate_df["year"] = king_guacate_df["year"].astype("category")
king_guacate_df["region"] = king_guacate_df["region"].astype("category")
king_guacate_df.dtypes

Unnamed: 0               int64
Date            datetime64[ns]
AveragePrice           float64
Total Volume           float64
4046                   float64
4225                   float64
4770                   float64
Total Bags             float64
Small Bags             float64
Large Bags             float64
XLarge Bags            float64
type                  category
year                  category
region                category
dtype: object

In [51]:
# Checking for missing Data
# We can't make assumptions that the data given is the clean and sound.

# pd.isna would return a new dataframe with False or True Values
# And then method chain nunique method.
pd.isna(king_guacate_df).nunique()

Unnamed: 0      1
Date            1
AveragePrice    1
Total Volume    1
4046            1
4225            1
4770            1
Total Bags      1
Small Bags      1
Large Bags      1
XLarge Bags     1
type            1
year            1
region          1
dtype: int64

Sweet!

So far we have proper data types, no missing values.

Next I would like to reorder the columns, reindex with the date, and drop some columns.

In [52]:
# Reorder the columns, reindex with the date, and drop some columns
king_guacate_df.columns
# I see the columns "Unnamed", "Total Bags", "Small Bags", "Large Bags", XLarge Bag", are not needed to since we've mentioned that we just needed Total Volume of avocados sold by date and location, by type, and at the average price.

Index(['Unnamed: 0', 'Date', 'AveragePrice', 'Total Volume', '4046', '4225',
       '4770', 'Total Bags', 'Small Bags', 'Large Bags', 'XLarge Bags', 'type',
       'year', 'region'],
      dtype='object')

In [53]:
# First let us set the index of the data frame from a range of numbers to the Date column
king_guacate_df = king_guacate_df.set_index("Date")

In [54]:
# Second let us drop the unwanted columns with using the .drop method
king_guacate_df = king_guacate_df.drop(["Unnamed: 0", "Total Bags", "Small Bags", "Large Bags", "XLarge Bags"], axis=1)
king_guacate_df.columns.to_list()

['AveragePrice',
 'Total Volume',
 '4046',
 '4225',
 '4770',
 'type',
 'year',
 'region']

In [55]:
# Finally We would like to reorder the columns to anticipate appended columns.
king_guacate_df = king_guacate_df[["year", "type", "AveragePrice", "Total Volume", "4046", "4225", "4770", "region"]]
king_guacate_df

year          type  AveragePrice  Total Volume     4046  \
Date                                                                  
2015-12-27  2015  conventional          1.33      64236.62  1036.74   
2015-12-20  2015  conventional          1.35      54876.98   674.28   
2015-12-13  2015  conventional          0.93     118220.22   794.70   
2015-12-06  2015  conventional          1.08      78992.15  1132.00   
2015-11-29  2015  conventional          1.28      51039.60   941.48   
...          ...           ...           ...           ...      ...   
2018-02-04  2018       organic          1.63      17074.83  2046.96   
2018-01-28  2018       organic          1.71      13888.04  1191.70   
2018-01-21  2018       organic          1.87      13766.76  1191.92   
2018-01-14  2018       organic          1.93      16205.22  1527.63   
2018-01-07  2018       organic          1.62      17489.58  2894.77   

                 4225    4770            region  
Date                                             
2015-12-27   54454.85   48.16            Albany  
2015-12-20   44638.81   58.33            Albany  
2015-12-13  109149.67  130.50            Albany  
2015-12-06   71976.41   72.58            Albany  
2015-11-29   43838.39   75.78            Albany  
...               ...     ...               ...  
2018-02-04    1529.20    0.00  WestTexNewMexico  
2018-01-28    3431.50    0.00  WestTexNewMexico  
2018-01-21    2452.79  727.94  WestTexNewMexico  
2018-01-14    2981.04  727.01  WestTexNewMexico  
2018-01-07    2356.13  224.53  WestTexNewMexico  

[18249 rows x 8 columns]

In [56]:
# Oops forgot to sort the dates when we converted the column to an index.
king_guacate_df.sort_index(inplace=True)
king_guacate_df

year          type  AveragePrice  Total Volume        4046  \
Date                                                                     
2015-01-04  2015       organic          1.75      27365.89     9307.34   
2015-01-04  2015       organic          1.49      17723.17     1189.35   
2015-01-04  2015       organic          1.68       2896.72      161.68   
2015-01-04  2015  conventional          1.52      54956.80     3013.04   
2015-01-04  2015       organic          1.64       1505.12        1.27   
...          ...           ...           ...           ...         ...   
2018-03-25  2018  conventional          1.36     908202.13   142681.06   
2018-03-25  2018  conventional          0.70    9010588.32  3999735.71   
2018-03-25  2018       organic          1.42     163496.70    29253.30   
2018-03-25  2018       organic          1.70     190257.38    29644.09   
2018-03-25  2018  conventional          1.34    1774776.77    63905.98   

                 4225       4770              region  
Date                                                  
2015-01-04    3844.81     615.28           Southeast  
2015-01-04   15628.27       0.00             Chicago  
2015-01-04     206.96       0.00  HarrisburgScranton  
2015-01-04   35456.88    1561.70          Pittsburgh  
2015-01-04    1129.50       0.00               Boise  
...               ...        ...                 ...  
2018-03-25  463136.28  174975.75             Chicago  
2018-03-25  966589.50   30130.82        SouthCentral  
2018-03-25    5080.04       0.00        SouthCentral  
2018-03-25   70982.10       0.00          California  
2018-03-25  908653.71     843.45             NewYork  

[18249 rows x 8 columns]

Looks good.

Now I want to save our modified data frame to a pickle file in the interim folder.

In [57]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html
king_guacate_df.to_pickle("./data/interim/avocado.pkl")